name: Steve Stephenson
description: Developer, Design, Artist
meta_description: "My personal site where I talk about work, life and everything in between."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://stevenstephenson.com'
google_analytics: 'UA-12387202-1'
disqus: true
disqus_shortname: 'stevenstephenson24'

# Details for the RSS feed generator
url:            'http://stevenstephenson.com'
author:         'Steve Stephenson'
authorTwitter:  'creativeowtlaw'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
